#!/usr/bin/env node
// Generates the in-conversation mode-switch skills (/claudekei:plan, /claudekei:sprint,
// /claudekei:analyze, /claudekei:orchestrate) from the primary agent definitions, so the
// agent file stays the single source of truth for each prompt.
//
//   node scripts/sync-modes.mjs          write skills/<command>/SKILL.md
//   node scripts/sync-modes.mjs --check  exit 1 if any generated file is stale

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const MODES = [
  {
    command: 'orchestrate',
    agent: 'orchestrator',
    title: 'Orchestrator',
    summary: 'delegation-first coordinator',
  },
  {
    command: 'plan',
    agent: 'planner',
    title: 'Planner',
    summary: 'interview-first planning, no implementation',
  },
  {
    command: 'sprint',
    agent: 'sprinter',
    title: 'Sprinter',
    summary: 'fast self-executing, no delegation',
  },
  {
    command: 'analyze',
    agent: 'business-analyst',
    title: 'Business Analyst',
    summary: 'market research, requirements, strategy; saves analysis to .business-analyst/',
  },
];

function agentBody(agent) {
  const source = readFileSync(join(ROOT, 'agents', `${agent}.md`), 'utf8');
  const match = /^---\n[\s\S]*?\n---\n/.exec(source);
  if (!match) throw new Error(`agents/${agent}.md has no frontmatter`);
  return source.slice(match[0].length).trim();
}

export function renderMode(mode) {
  const others = MODES.filter((m) => m !== mode)
    .map((m) => `/claudekei:${m.command}`)
    .join(', ');
  return `---
name: ${mode.command}
description: 'Switch this conversation to claudekei ${mode.title} mode (${mode.summary}).'
disable-model-invocation: true
---

<!-- Generated by scripts/sync-modes.mjs from agents/${mode.agent}.md. Do not edit by hand. -->

From now on in this conversation, act as the claudekei **${mode.title}** until the user switches mode again (${others}). These instructions replace any previous primary-agent role and workflow in this conversation.

<mode-instructions>
${agentBody(mode.agent)}
</mode-instructions>

If the user included a request with this command, start on it now: $ARGUMENTS
`;
}

function main() {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const mode of MODES) {
    const file = join(ROOT, 'skills', mode.command, 'SKILL.md');
    const expected = renderMode(mode);
    let current = null;
    try {
      current = readFileSync(file, 'utf8');
    } catch {}
    if (current === expected) continue;
    if (check) {
      console.error(`stale: skills/${mode.command}/SKILL.md`);
      stale++;
    } else {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, expected);
      console.log(`wrote skills/${mode.command}/SKILL.md`);
    }
  }
  if (stale) {
    console.error('Run `node scripts/sync-modes.mjs` to regenerate.');
    process.exit(1);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
